# Generated by Django 2.2.12 on 2020-10-24 04:57

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_line_demographic_survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'red_line_demographic_survey_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_line_demographic_survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'red_line_demographic_survey_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('age', otree.db.models.IntegerField(null=True, verbose_name='What is your age?')),
                ('gender', otree.db.models.StringField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer not to respond', 'Prefer not to respond')], max_length=10000, null=True, verbose_name='What is your gender?')),
                ('nationality', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What is your nationality?')),
                ('race', otree.db.models.StringField(choices=[('White', 'White'), ('Asian', 'Asian'), ('Black/African', 'Black/African'), ('Other', 'Other'), ('Prefer not to respond', 'Prefer not to respond')], max_length=10000, null=True, verbose_name='What is your race?')),
                ('is_student', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Are you a student?')),
                ('student_semesters', otree.db.models.IntegerField(null=True, verbose_name='How many semesters did you study so far in total?')),
                ('student_program', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What do you study (program/course)?')),
                ('highest_degree', otree.db.models.StringField(choices=[('High School Diploma or equivalent', 'High School Diploma or equivalent'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=10000, null=True, verbose_name='What is your highest educational degree?')),
                ('current_occupation', otree.db.models.StringField(max_length=10000, null=True, verbose_name='What is your current occupation?')),
                ('similar_experiment_before', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Have you been part of a similar experiment before?')),
                ('find_instructions_clear', otree.db.models.StringField(choices=[('Strongly disagree', 'Strongly disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly agree', 'Strongly agree')], max_length=10000, null=True, verbose_name='Do you find the experiment instruction clear?')),
                ('comments', otree.db.models.LongStringField(blank=True, null=True, verbose_name='Comments about this experiment')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='red_line_demographic_survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_line_demographic_survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_line_demographic_survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_line_demographic_survey.Subsession')),
            ],
            options={
                'db_table': 'red_line_demographic_survey_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_line_demographic_survey.Subsession'),
        ),
    ]
