# Generated by Django 2.2.12 on 2020-11-16 01:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('red_line_demographic_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=otree.db.models.IntegerField(null=True, verbose_name='年齡'),
        ),
        migrations.AlterField(
            model_name='player',
            name='comments',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='對此實驗，歡迎樓下任何建議'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_occupation',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='請問您目前的職業是？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='find_instructions_clear',
            field=otree.db.models.StringField(choices=[('非常不同意', '非常不同意'), ('不同意', '不同意'), ('沒意見', '沒意見'), ('同意', '同意'), ('非常同意', '非常同意')], max_length=10000, null=True, verbose_name='請問您認為實驗說明夠詳細嗎？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.StringField(choices=[('女', '女'), ('男', '男'), ('其他', '其他'), ('傾向不告知', '傾向不告知')], max_length=10000, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='player',
            name='highest_degree',
            field=otree.db.models.StringField(choices=[('高中或等同高中學歷', '高中或等同高中學歷'), ('學士', '學士'), ('碩士', '碩士'), ('PhD', 'PhD')], max_length=10000, null=True, verbose_name='What is your highest educational degree?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_student',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='您是學生嗎'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='國籍'),
        ),
        migrations.AlterField(
            model_name='player',
            name='similar_experiment_before',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='請問您曾經參加過類似的實驗嗎？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='student_program',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='請問您的主修科系為？'),
        ),
        migrations.AlterField(
            model_name='player',
            name='student_semesters',
            field=otree.db.models.IntegerField(null=True, verbose_name='請問您目前共修習多少學期的課程？'),
        ),
    ]
