# Generated by Django 2.2.12 on 2020-11-16 01:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('red_line_demographic_survey', '0002_auto_20201116_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='highest_degree',
            field=otree.db.models.StringField(choices=[('高中或等同高中學歷', '高中或等同高中學歷'), ('學士', '學士'), ('碩士', '碩士'), ('PhD', 'PhD')], max_length=10000, null=True, verbose_name='請問您的最高學歷為'),
        ),
    ]
