# Generated by Django 2.2.12 on 2020-11-16 14:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('red_line_demographic_survey', '0003_auto_20201116_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='comments',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='對此實驗，歡迎留下任何建議'),
        ),
    ]
